- name: Check if the cluster exists
  tags: check_cluster
  ansible.builtin.include_tasks: check_cluster.yml

- name: Create cluster if it does not exist
  tags: create_cluster
  ansible.builtin.include_tasks: create_cluster.yml
  when: not cluster_exists_flag

# Run the remaining tasks only if the cluster exists or was created

- name: Configure cluster
  tags: config_cluster
  when: cluster_exists_flag
  block:

    - name: Create servers on Nodes for Cluster
      tags: create_servers
      throttle: 1
      block:
        - name: Include create_servers tasks
          ansible.builtin.include_tasks: create_servers.yml

    - name: Set security properties (user & password)
      tags: set_security
      ansible.builtin.include_tasks: set_security.yml

    - name: Restart Node Agents
      tags: restart_node_agents
      ansible.builtin.include_tasks: restart_nodeagent.yml

    - name: Restart Deployment Manager
      tags: restart_dmgr
      run_once: true
      ansible.builtin.include_tasks: restart_dmgr.yml

    - name: Create applogs directory
      tags: create_applogs_dir
      ansible.builtin.file:
        path: "{{ was_path }}/profiles/{{ env_vars.profile_name }}/logs/{{ env_vars.server_name }}/applogs"
        state: directory
        owner: webadmn
        group: webadmn
        mode: '0755'

- name: Check if the Cluster Member Servers directory exists
  tags: check_cluster_members
  ansible.builtin.stat:
    path: "{{ node_server_dir }}"
  register: node_server_exists

# Run the remaining tasks only if the node servers exists or created
- name: Configure Node Servers
  tags: config_nodeservers
  when: node_server_exists.stat.exists
  block:

    - name: Set Profile JVM Size
      tags: jvm
      ansible.builtin.include_tasks: jvm_config.yml

    - name: Setup profile ports
      tags: port_config
      ansible.builtin.include_tasks: port_config.yml
      loop: "{{ profile_port_list }}"
      loop_control:
        loop_var: profile_port
      when: profile_port_list is defined

    - name: Setup Virtual hosts and Host aliases
      tags: vhosts
      ansible.builtin.include_tasks: virtualhost_alias_config.yml
      loop: "{{ virtual_host_list }}"
      loop_control:
        loop_var: virtual_host
      when: virtual_host_list is defined

    - name: Setup JDBC providers
      tags: jdbc
      ansible.builtin.include_tasks: jdbc_provider_config.yml
      loop: "{{ jdbc_provider_list }}"
      loop_control:
        loop_var: jdbc_provider
      when: jdbc_provider_list is defined

    - name: Setup JDBC data sources
      tags: jdbc
      no_log: true # To avoid printing user/pw in output
      ansible.builtin.include_tasks: jdbc_datasource_config.yml
      loop: "{{ env_vars.jdbc_datasource_list }}"
      loop_control:
        loop_var: jdbc_datasource
      when: env_vars.jdbc_datasource_list is defined
