#
#       ReviewCase Editor property file
# ----------------------------------------------------------------------------------------------
#   This file contains the section
#   I   ) CTRL-PARAMERTER  never change any parameter in section Ia, as this are parameter to
#                              influence the behaviour of the embedded control
#       II      ) AppServer        Settings for application server
#       III     ) DATABASE-CONN    All connections to the database oracle 10g
#   VI  ) Uncategorized    parms, thatz won't fit to one of above categories
# ----------------------------------------------------------------------------------------------

# ------------------
# I CTRL-PARAMETER -
# ------------------
#1a) 'unchangeable' parameter
ctrlparm_showTools=0
ctrlparm_showPanes=1
ctrlparm_initialPane=1
ctrlparm_loginMode=WIN
ctrlparm_UserGroupMode=1
ctrlparm_debug=false

#1b) stage depended parameters for thunderhead
th_service_url={{ env_vars.th_service_url }}

# ------------------------------------------------------------------------
# II App Server Setting for getting the context ...
# -----------------------------------------------------------------------
appsrv_url={{ env_vars.appsrv_url }}

# ------------------------------------------------------------------------
# III Database Connetions
# ------------------------------------------------------------------------
jdbcdriver=oracle.jdbc.OracleDriver
jdbctyp=jdbc:oracle:thin
dbservername={{ env_vars.dbservername }}
dbport={{ env_vars.dbport }}
# alternative serverport for DEV available  at 1570
dbscheme={{ vault[app].dbscheme }}
dbuser={{ vault[app].dbuser }}
dbpass={{ vault[app].dbpass }}

#added properties for symphony database connection - START
dbservername_data={{ env_vars.dbservername_data }}
dbport_data={{ env_vars.dbport_data }}
dbscheme_data={{ vault[app].dbscheme_data }}
dbuser_data={{ vault[app].dbuser_data }}
dbpass_data={{ vault[app].dbpass_data }}

#added properties for symphony database connection - END

 #-----------------------------------------------------------------------
 # IV : untecategorized paramters
 # ----------------------------------------------------------------------
 # description of the application for the header line
 appdesc={{ env_vars.appdesc }}

  #-----------------------------------------------------------------------
 # IV : copy sections
 # ----------------------------------------------------------------------
 # fix for defect 5659 by INSPAL1
 # all regions and sections to be copied are maintained here.
 sections={{ env_vars.sections }}
 