#mrf50406 CHG0070455 Updating Risknet targets to new Azure infrastructure
WATSON_SERVICE={{ env_vars.watson_service }}
CLIENT_ID={{ vault[app].client_id }}
CLIENT_SECRET={{ vault[app].client_secret }}
WATSON_AUTH_SERVICE={{ env_vars.watson_auth_service }}
GRANT_TYPE=client_credentials
SCOPE={{ env_vars.scope }}
