---
galaxy_info:
  author: Atradius Infrastructure Team
  description: Remove systemd services for WebSphere Application Server standalone instances
  license: proprietary
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - websphere
    - systemd
    - service
    - linux
    - removal

dependencies: []
