#################################  Web Service URL  #################################
URL_WS_CLD={{ env_vars.url_ws_cld }}
URL_WS_CLD_LINK1={{ env_vars.url_ws_cld_link1 }}
URL_WS_CLD_LINK2={{ env_vars.url_ws_cld_link2 }}

URL_WS_INVOICE={{ env_vars.url_ws_invoice }}
URL_WS_INVOICE_LINK1={{ env_vars.url_ws_invoice_link1 }}

URL_WS_POLICY={{ env_vars.url_ws_policy }}
URL_WS_POLICY_LINK1={{ env_vars.url_ws_policy_link1 }}

URL_WS_DECLARATION={{ env_vars.url_ws_declaration }}
URL_WS_DECLARATION_LINK1={{ env_vars.url_ws_declaration_link1 }}

URL_WS_ORG={{ env_vars.url_ws_org }}
URL_WS_ORG_LINK1={{ env_vars.url_ws_org_link1 }}
URL_WS_ORG_LINK2={{ env_vars.url_ws_org_link2 }}

URL_WS_ORBS={{ env_vars.url_ws_orbs }}
URL_WS_ORBS_LINK1={{ env_vars.url_ws_orbs_link1 }}

URL_WS_OUTPUTWS={{ env_vars.url_ws_outputws }}
URL_WS_OUTPUTWS_LINK1={{ env_vars.url_ws_outputws_link1 }}

URL_WS_GEN_OUTPUTWS={{ env_vars.url_ws_gen_outputws }}
URL_WS_GEN_OUTPUTWS_LINK1={{ env_vars.url_ws_gen_outputws_link1 }}

URL_WS_BUYER={{ env_vars.url_ws_buyer }}
URL_WS_BUYER_LINK1={{ env_vars.url_ws_buyer_link1 }}

URL_WS_CLEAR={{ env_vars.url_ws_clear }}
URL_WS_CLEAR_LINK1={{ env_vars.url_ws_clear_link1 }}

URL_WS_COMPOSITE={{ env_vars.url_ws_composite}}
URL_WS_COMPOSITE_LINK1={{ env_vars.url_ws_composite_link1 }}
URL_WS_COMPOSITE_LINK2={{ env_vars.url_ws_composite_link2 }}

URL_DSB={{ env_vars.url_dsb }}
URL_DSB_LINK1={{ env_vars.url_dsb_link1 }}
URL_DSB_LINK2={{ env_vars.url_dsb_link2 }}

#################################  Daemons URL  #################################
URL_DP_INVOICE={{ env_vars.url_dp_invoice }}
URL_DP_INVOICE_LINK1={{ env_vars.url_dp_invoice_link1 }}
URL_DP_INVOICE_LINK2={{ env_vars.url_dp_invoice_link2 }}

URL_DP_CLD={{ env_vars.url_dp_cld}}
URL_DP_CLD_LINK1={{ env_vars.url_dp_cld_link1 }}
URL_DP_CLD_LINK2={{ env_vars.url_dp_cld_link2 }}

URL_DP_CLAIMS={{ env_vars.url_dp_claims}}
URL_DP_CLAIMS_LINK1={{ env_vars.url_dp_claims_link1 }}
URL_DP_CLAIMS_LINK2={{ env_vars.url_dp_claims_link2 }}

URL_DP_MPD={{ env_vars.url_dp_mpd }}
URL_DP_MPD_LINK1={{ env_vars.url_dp_mpd_link1 }}
URL_DP_MPD_LINK2={{ env_vars.url_dp_mpd_link2 }}

URL_DP_GENERIC={{ env_vars.url_dp_generic }}
URL_DP_GENERIC_LINK1={{ env_vars.url_dp_generic_link1 }}
URL_DP_GENERIC_LINK2={{ env_vars.url_dp_generic_link2 }}

URL_DP_FINANCE={{ env_vars.url_dp_finance}}
URL_DP_FINANCE_LINK1={{ env_vars.url_dp_finance_link1 }}
URL_DP_FINANCE_LINK2={{ env_vars.url_dp_finance_link2 }}

URL_DP_DSB={{ env_vars.url_dp_dsb}}
URL_DP_DSB_LINK1={{ env_vars.url_dp_dsb_link1 }}
URL_DP_DSB_LINK2={{ env_vars.url_dp_dsb_link2 }}

URL_DP_GENLETTER={{ env_vars.url_dp_genletter}}
URL_DP_GENLETTER_LINK1={{ env_vars.url_dp_genletter_link1 }}
URL_DP_GENLETTER_LINK2={{ env_vars.url_dp_genletter_link2 }}


#################################  Thunderhead properties  #################################
#URL of ThunderHeadResponseProcessor
PROCESSOR={{ env_vars.th_processor }}

URL_WS_TH={{ env_vars.url_ws_th }}
URL_WS_TH_LINK1={{ env_vars.url_ws_th_link1 }}
URL_WS_TH_LINK2={{ env_vars.url_ws_th_link2 }}

#THUNDERHEAD RESPONSE TOPIC
THUNDERHEAD_QUEUE_PROVIDER_URL={{ env_vars.thunderhead_queue_provider }}
THUNDERHEAD_QUEUE_PROVIDER_URL1={{ env_vars.thunderhead_queue_provider_url1 }}
THUNDERHEAD_QUEUE_PROVIDER_URL2={{ env_vars.thunderhead_queue_provider_url2 }}

#Added a configurable parameter for thunderhead batch
TH_BATCH_CONFIG=507000009
TH_BATCH_PREFIX={{ env_vars.th_batch_prefix }}
WS_TH_USERID={{ vault[app].ws_th_userid }}
WS_TH_PASSWORD=
THUSERID={{ vault[app].th_userid }}
THPASSWORD={{ vault[app].th_password }}

THUNDERHEAD_QUEUE_JMS_CONNECTION_FACTORY=jms/RemoteConnectionFactory
THUNDERHEAD_QUEUE_JMS_QUEUE_REQ=queue/thunderhead/JobRequests
THUNDERHEAD_QUEUE_JMS_QUEUE_RES=queue/thunderhead/Responses


#################################  SMTP Details  #################################
SMTP_MAIL_FROM={{ env_vars.mail_from }}
SMTP_MAIL_TO=operations@atradius.com;schedulingteam@atradius.com
SMTP_MAIL_SUBJECT=OPUS Status update: SMTP connection restored
SMTP_MAIL_SESSION=jndi/defaultMail


#################################  Application Constants  #################################
USE_JMS=true
JMS_TIMEOUT=300
REVIEW_CASE_TIMEOUT=300
SMTP_TIMEOUT=300
HEALTH_CHECK_TIMEOUT=300
ANNIHILATION_TIMEOUT=10800
REPROCESS_TIMEOUT=600
ENVIRONMENT={{ env_vars.env_name }}

#Element for start/stop of ReviewCase Unit in Monitoring tool
REVIEW_CASE_FLAG=true

##Synchronization Gap TimeOut
SYNCH_GAP_TIMEOUT=3600
AUTO_SYNCH_TIMEOUT=86400


#################################  CIBT/BBT Common Properties  #################################
UPDATE_STATUS_TIMEOUT=300

{{ env_vars.oauth_token_url_varname }}={{ env_vars.oauth_token_url }}

########## CBP Properties ##########
CBP_WS_API_TYPE=SOAP
CBP_ENV={{ env_vars.cbp_env }}
ORIGIN_ID=OPUS_SYSTEM
ORIGIN_APPLICATION={{ env_vars.origin_application }}
ORIGIN_SERVICE=Thunderhead
INVOCATION_SERVICE=letter-update

{% if env_code in ['FATW', 'FATF'] %}
{{ env_vars.oauth_token_url_varname2 }}={{ env_vars.oauth_token_url_2 }}
# CBP DEV Properties
CBP_DEV_UPDATE_URL={{ env_vars.cbp_dev_update_url }}
CBP_DEV_CLIENT_ID={{ vault[app].cbp_dev_client_id }}
CBP_DEV_CLIENT_SECRET={{ vault[app].cbp_dev_client_secret }}
CBP_DEV_SCOPE={{ env_vars.cbp_dev_scope }}
CBP_DEV_IDENTITY_DOMAIN={{ env_vars.cbp_dev_identity_domain }}
# CBP SIT Properties
CBP_SIT_UPDATE_URL={{ env_vars.cbp_sit_update_url }}
CBP_SIT_CLIENT_ID={{ vault[app].cbp_sit_client_id }}
CBP_SIT_CLIENT_SECRET={{ vault[app].cbp_sit_client_secret }}
CBP_SIT_SCOPE={{ env_vars.cbp_sit_scope }}
CBP_SIT_IDENTITY_DOMAIN={{ env_vars.cbp_sit_identity_domain }}
{% endif %}

########## CIBT Properties ##########
CIBT_WS_API_TYPE=REST
{{ env_vars.cibt_update_url_varname }}={{ env_vars.cibt_update_url }}
CIBT_ORIGIN_ID={{ vault[app].cibt_client_id }}
CIBT_ORIGIN_APPLICATION=CIBT
CIBT_ENV={{ env_vars.cibt_env }}
{{ env_vars.cibt_client_id_varname }}={{ vault[app].cibt_client_id }}
{{ env_vars.cibt_client_secret_varname }}={{ vault[app].cibt_client_secret }}
{{ env_vars.cibt_scope_varname }}={{ env_vars.cibt_scope }}
{{ env_vars.cibt_identity_domain_varname }}={{ env_vars.cibt_identity_domain }}

########## ARCADE Properties ##########
ARCADE_WS_API_TYPE=REST
{{ env_vars.arcade_update_url_varname }}={{ env_vars.arcade_update_url }}
ARCADE_ORIGIN_ID={{ vault[app].arcade_client_id }}
ARCADE_ORIGIN_APPLICATION=CIBT
ARCADE_ENV={{ env_vars.arcade_env }}
{{ env_vars.arcade_client_id_varname }}={{ vault[app].arcade_client_id }}
{{ env_vars.arcade_client_secret_varname }}={{ vault[app].arcade_client_secret }}
{{ env_vars.arcade_scope_varname }}={{ env_vars.arcade_scope }}
{{ env_vars.arcade_identity_domain_varname }}={{ env_vars.arcade_identity_domain }}
