JNDI_URL=iiop://localhost:{{ env_vars.was_bootstrap_port }}
JNDI_DS_SYMPHONY={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].sym_db_name)) | join(" ") }}
JNDI_DS_REPORTS={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].rep_db_name)) | join(" ") }}

BIPSERVICE_ENDPOINT={{ env_vars.bipservice_endpoint }}
FUTURESTATE_ENDPOINT={{ env_vars.futurestate_endpoint }}

networkdrive.folder.monitoring=/Monitoring
networkdrive.folder.notices=/Notices
networkdrive.folder.splittedbundle=/SplittedBundle
networkdrive.folder.mappings=/Mapping_Files
networkdrive.folder.error=/error
networkdrive.folder.structured=/Structured_Data
networkdrive.folder.unstructured=/Attachments_to_Genesis
networkdrive.folder.originals=/OriginalFiles
networkdrive.folder.parent={{ env_vars.networkdrive_folder_parent }}

Product.Monitoring=Monitoring
Product.Notices=Notices
bip.coface.country.codes=2,3,4,5,6,7,8,9,11
bip.coface.infosource.codes=126,139,133,142,146,7912123,826,969,16905047
bip.coface.infosource.partyid=HU,CZ,PL,SK,SI,HR,BG,RO,RS
cofaceUser={{ vault[app].coface_user }}
cofacePassword={{ vault[app].coface_password }}
cofaceURL={{ env_vars.coface_url }}
cofaceClientReportTimeout=180000
cofaceClientNoticestTimeout=180000
cofaceMaxNumberSearchHits=40
cofaceStartDate=
cofaceEndDate=
cofaceDownloadNotices=Y
cofaceDownloadReports=Y
cofaceDirectory=/BIPMONITORINGLOADS/COFNOTICES/transit