# The contents of this property file can be reloaded via index.jsp
# Author Nikhil , EVC project
genesis.user={{ vault[app].gbip_genesis_user }}
genesis.password={{ vault[app].gbip_genesis_password }}
genesis.webserviceURI={{ env_vars.genesis_webservice_uri }}
genesis.Document_Class=BUINF_C1
# All genesis Indexes should start with genesis.index ,code will automatically pick them up
genesis.index.Capture_Location=CRDIFF
genesis.index.Document_File_Type=BUINF
genesis.index.Document_Type=101A
genesis.index.Format_Type=ACROB
genesis.index.Security=N

# General messages
bip.reportdisplay.notavailable = Report not Available

# EVC Properties
bip.evc.report.countryCode=DE
bip.evc.report.legitimate_interest=LEIN-100
bip.evc.search.searchtype=SETY-1
bip.evc.search.registertype=RETY
bip.evc.MaxNumberSearchHits=40
bip.evc.RequestTimeout=360000
bip.evc.logon.keylist.message = The keylist version at EVC is different
bip.evc.preferred.language={{ env_vars.bip_evc_preferred_language}}
bip.evc.searchheader.transactionreference={{ env_vars.transaction_reference }}

# Properties for checkMonitoringStatus
bip.evc.maxresults=500
bip.evc.checkMonitoringStatus.CMOF.InclstdMonitoringExt=false
bip.evc.checkMonitoringStatus.CMOF.InclExtMonOrder=false
bip.evc.checkMonitoringStatus.InclstdMonitoringExt=true
bip.evc.checkMonitoringStatus.InclExtMonOrder=true
bip.evc.checkMonitoringStatus.InclExtMonPlsOrder={{ env_vars.bip_evc_checkmonitoringstatus_inclextmonplsorder }}
bip.evc.checkMonitoringStatus.InclExtMonPlsActive={{ env_vars.bip_evc_checkmonitoringstatus_inclextmonplsactive }}
bip.evc.checkMonitoringStatus.InclExtMonActive=true
#Properties for Change Extended Monitoring
bip.evc.changeExtendedMonitoring.ExtendedMonitoringPlus=false
#Properties Report Type or product type,this is only used for comparision
bip.evc.checkMonitoringStatus.MOA.productType=PRTY-1002
bip.evc.requestOnlineReport.CR.productType=PRTY-3
bip.evc.orderrequest.BR.productType=PRTY-2
bip.evc.CMON.MaxDate=31-12-4712
bip.evc.CMOF.Extendedmonitoringplus=false
bip.evc.EVCReportMapper.updatenote.retcode=NU
bip.evc.checkMonitoringStatus.SplerrorCode=ER-9
bip.evc.constantmonitoring.requestDelayedOnlineReports=false

#EVC Header information
bip.evc.requestheader.Communicationlanguage={{ env_vars.bip_evc_requestheader_communicationlanguage }}
bip.evc.requestheader.clientapplicationversion=100
bip.evc.requestheader.clientapplicationname={{ env_vars.bip_evc_requestheader_clientapplicationname }}
bip.evc.requestheader.keylistversion=10
bip.evc.requestheader.transactionreference=Atradius

# Added entry for MailBoxDirectoryRead

bip.evc.MailBoxDirectory.Numberofentries=500
bip.evc.MailBoxDirectory.Deliverytypereport=true
bip.evc.MailBoxDirectory.Deliverytypestatusreply=true
bip.evc.MailBoxDirectory.Deliverytypestockdelivery=false
bip.evc.MailBoxDirectory.Deliverytypesupplement=true
bip.evc.MailBoxDirectory.Deliverytypeupdate=true
bip.evc.MailBoxDirectory.Entriesread=false
bip.evc.MailBoxDirectory.Entriesunread=true
bip.evc.MailBoxDirectory.Identificationnumber=
bip.evc.MailBoxDirectory.Openorders=false
bip.evc.MailBoxDirectory.Pagereference=
bip.evc.MailBoxDirectory.Referencenumber=
bip.evc.MailBoxDirectory.Callperiod.Dateend=
bip.evc.MailBoxDirectory.Callperiod.Datestart=
bip.evc.MailBoxDirectory.Creationperiod.Dateend=
bip.evc.MailBoxDirectory.Creationperiod.Datestart=
bip.evc.MailBoxDirectory.Orderperiod.Dateend=
bip.evc.MailBoxDirectory.Orderperiod.Datestart=

# For Order (Inquiry)
bip.evc.orderrequest.orderType=ORTY-1

BUSINESS_LOG_FOLDER=DEU_125
bip.evc.search.registertypeA=RETY-DE-1
bip.evc.search.registertypeB=RETY-DE-2
bip.evc.search.registertypeP=RETY-DE-3
bip.evc.search.registertypeC=RETY-DE-4
bip.evc.search.registertypeV=RETY-DE-5
bip.evc.search.registertypeRETYA=A
bip.evc.search.registertypeRETYB=B
bip.evc.search.registertypeRETYP=P
bip.evc.search.registertypeRETYC=C
bip.evc.search.registertypeRETYV=V

bip.evc.validationerror=PC

#crn89085 further bip properties

bip.dnb.AddRegistration.Customer_Account_ID=
bip.dnb.AddRegistration.Endorsement=
bip.dnb.AddRegistration.Expiration_Date=
bip.dnb.AddRegistration.Reason_Code=
bip.dnb.AddRegistration.Do_not_Renew=
bip.dnb.AddRegistration.Trade_up_Indicator=

bip.dnb.GetRegistrationActivity.Customer_Account_ID=
bip.dnb.GetRegistrationActivity.Endorsement=
bip.dnb.GetRegistrationActivity.Activity_Codes=
bip.dnb.GetRegistrationActivity.Pending_Activity_only=
bip.dnb.GetRegistrationActivity.User_Level=
bip.dnb.GetRegistrationActivity.Result_Ticket=
bip.dnb.GetRegistrationActivity.Activity_Date_From=
bip.dnb.GetRegistrationActivity.Activity_Date_To=
bip.dnb.GetRegistrationActivity.Renewal_Date_From=
bip.dnb.GetRegistrationActivity.Renewal_Date_To=
bip.dnb.GetRegistrationActivity.Expiration_Date_From=
bip.dnb.GetRegistrationActivity.Expiration_Date_To=
bip.dnb.GetRegistrationActivity.Character_Set_Override=

bip.dnb.ModifyRegistration.Customer_Account_ID=
bip.dnb.ModifyRegistration.New_Account_ID=
bip.dnb.ModifyRegistration.Customer_Endorsement=
bip.dnb.ModifyRegistration.New_Endorsement=
bip.dnb.ModifyRegistration.Cancel_Registration=
bip.dnb.ModifyRegistration.Un-cancel_Registration=
bip.dnb.ModifyRegistration.Renew_Registration=
bip.dnb.ModifyRegistration.Do_not_Renew_Registration=N
bip.dnb.ModifyRegistration.Character_Set_Override=
bip.dnb.ModifyRegistration.Expiration_Date=
bip.dnb.RequestTimeout=360000

bip.dnb.GetNotifications.DnB_DUNS_Number=
bip.dnb.GetNotifications.CountryCode=
bip.dnb.GetNotifications.Product_Name=
bip.dnb.GetNotifications.Notification_Level=
bip.dnb.GetNotifications.Endorsement=
bip.dnb.GetNotifications.User_Level=
bip.dnb.GetNotifications.Detection_Date_From=
bip.dnb.GetNotifications.Detection_Date_To=
bip.dnb.GetNotifications.Received_Date_From=
bip.dnb.GetNotifications.Received_Date_To=
bip.dnb.GetNotifications.Active_Registrations_only=True
bip.dnb.GetNotifications.Pending_Notices_only={{ env_vars.pending_notices }}
bip.dnb.GetNotifications.Do_not_Mark_as_Read=False
bip.dnb.GetNotifications.Character_Set_Override=

bip.dnb.GetRegistrationList.RequestTimeout=360000
bip.dnb.GetRegistrationList.DnB_DUNS_Number=
bip.dnb.GetRegistrationList.CountryCode=
bip.dnb.GetRegistrationList.Product_Name=
bip.dnb.GetRegistrationList.Notification_Level=
bip.dnb.GetRegistrationList.Customer_Account_ID=
bip.dnb.GetRegistrationList.Endorsement=
bip.dnb.GetRegistrationList.User_Level=
bip.dnb.GetRegistrationList.Result_Ticket=
bip.dnb.GetRegistrationList.Last_Update_Date_From=
bip.dnb.GetRegistrationList.Last_Update_Date_To=
bip.dnb.GetRegistrationList.Renewal_Date_From=
bip.dnb.GetRegistrationList.Renewal_Date_To=
bip.dnb.GetRegistrationList.Expiration_Date_From=
bip.dnb.GetRegistrationList.Expiration_Date_To=
bip.dnb.GetRegistrationList.Character_Set_Override=
