# Author Ajay , EVC project
bip.evc.searchheader.useraccount={{ vault[app].evc_searchheader_useraccount }}
bip.evc.searchheader.generalpassword={{ vault[app].evc_searchheader_generalpassword }}
bip.evc.searchheader.individualpassword={{ vault[app].evc_searchheader_individualpassword }}f
bip.evc.requestheader.useraccount={{ vault[app].evc_requestheader_useraccount }}
bip.evc.requestheader.generalpassword={{ vault[app].evc_requestheader_generalpassword }}
bip.evc.requestheader.individualpassword={{ vault[app].evc_requestheader_individualpassword }}
