# folder where queue Readers dump messages to files
stageconfig.datafile=/home/webadmn/bip

# log4j configuration file
stageConfig.log4jConfig=

# proxy server - should be set to empty value on all servers
stageConfig.proxyHost=
stageConfig.proxyPort=

# connection to provider Graydon UK (source879)
stageConfig.graydonUkUrl=https://www.webservices.graydon.co.uk:443/CompanyData_webservice/services/SOAPPort

# Graydon UK user/pass
stageConfig.graydonUkUser={{ vault[app].graydonuk_user }}
stageConfig.graydonUkPassword={{ vault[app].graydonuk_password }}

# Graydon UK FTP download path
stageConfig.graydonUkDirectory={{ env_vars.stageconfig_graydonukdirectory }}

# Graydon BE Monitoring Files path
stageConfig.graydonBeDirectory=/BIPMONITORINGLOADS/BE/transit

# Graydon NL Monitoring Files path
stageConfig.graydonNlDirectory=/BIPMONITORINGLOADS/NL/transit

#TEMPORARY new files path for CofaceEE monitoring notices until Coface fix issue at their end - MRF25123
stageConfig.cofaceDirectory=/BIPMONITORINGLOADS/EENOTICES-TEMP/transit

#mrf27547
stageConfig.evcDirectory={{ env_vars.stageconfig_evc_directory }}

stageConfig.graydonNlSearchUrl=https://services.graydon.nl/XSellence/services/companySearch
stageConfig.graydonNlReportsUrl=https://services.graydon.nl/XSellence/services/companyInquiry

# Required to make MBeans work
stageConfig.serviceEndpoint={{ env_vars.stageconfig_serviceendpoint }}

# connection to provider experian (source713)
stageConfig.experianIrlUrl=http://194.60.177.140/Images/XML/XMLgateway.asp

# Graydon NL user/pass
stageConfig.graydonNlUser={{ vault[app].graydonnl_user }}
stageConfig.graydonNlPassword={{ vault[app].graydonnl_password }}
stageConfig.graydonNlServiceNumber=50696
stageConfig.graydonNlMaxNumberSearchHits=40

# Graydon NL HTTP Connection Timeout for their Soap Client Proxy
stageConfig.graydonNlClientReportTimeout=180000

# Graydon BE user/pass
stageConfig.graydonBeUser={{ vault[app].graydonbe_user }}
stageConfig.graydonBePassword={{ vault[app].graydonbe_password }}
stageConfig.graydonBeClientNumber={{ env_vars.stageconfig_graydonbeclientnumber  }}
stageConfig.graydonBeUrl=https://193.111.225.10:10443/servlet/XmlAccessClient

# DNB USA user/pass
stageConfig.DnBUser={{ vault[app].dnb_user }}
stageConfig.DnBPassword={{ vault[app].dnb_password }}
stageConfig.DnBUser11517859={{ vault[app].dnb_user11517859 }}
stageConfig.DnBPassword11517859={{ vault[app].dnb_password11517859 }}
stageConfig.DnBMaxNumberSearchHits=50
stageConfig.DnBURL=https://toolkit.dnb.com/ws/DNB_WebServices.Providers.OrderAndInvestigations.GDP_V3:wsp_GDP_V3
stageConfig.DnBSearchURL=https://toolkit.dnb.com/ws/DNB_WebServices.Providers.LookUp:wsp_LookUp
stageConfig.DnBCharSet=ISO-8859-1

# COFACE East Europe user/pass (was XBRL)
stageConfig.cofaceUser={{ vault[app].coface_user }}
stageConfig.cofacePassword={{ vault[app].coface_password }}
stageConfig.cofaceMaxNumberSearchHits=40
stageConfig.cofaceURL={{ env_vars.stageconfig_cofaceurl }}
stageConfig.cofaceStartDate=
stageConfig.cofaceEndDate=
stageConfig.cofaceDownloadNotices=Y
stageConfig.cofaceDownloadReports=Y
stageConfig.cofaceClientReportTimeout=180000
stageConfig.cofaceClientNoticestTimeout=180000

# CRN Nikhil on 30 Sep 2010 CRN84493
stageConfig.DnBUser880={{ vault[app].dnb_user880 }}
stageConfig.DnBPassword880={{ vault[app].dnb_password880 }}
stageConfig.DnBUser14625239={{ vault[app].dnb_user14625239 }}
stageConfig.DnBPassword14625239={{ vault[app].dnb_password14625239 }}
stageConfig.DnBUser14371663={{ vault[app].dnb_user14371663 }}
stageConfig.DnBPassword14371663={{ vault[app].dnb_password14371663 }}
# CRN95532
stageConfig.DnB.BIRURL = https://toolkit.dnb.com/ws/DNB_WebServices.Providers.OrderAndInvestigations.OtherProducts.BIR_V1:wsp_BIR_V1

# CRN 89085
stageConfig.DnB.GetNotificationsURL=https://toolkit.dnb.com/ws/DNB_WebServices.Providers.GetNotifications_V1:wsp_GetNotifications_V1
stageConfig.DnB.StartDate=
stageConfig.DnB.EndDate=
stageConfig.DnBMonUser={{ vault[app].dnb_mon_user }}
stageConfig.DnBMonPassword={{ vault[app].dnb_mon_password }}
stageConfig.DnB.GetRegiListDownloadURL=https://toolkit.dnb.com/ws/DNB_WebServices.Providers.GetRegistrationList_V1:wsp_GetRegistrationList_V1

# Settings for EVC
stageConfig.evcURL={{ env_vars.evc_url }}
stageConfig.bipproperties={{ env_vars.stageconfig_bipproperties}}
stageConfig.evcSearchURL={{ env_vars.evc_searchurl }}

# The below property will be used in various BIP-USA components # to avoid clashes with the Cryptix Encryption library...
# This property value is mandatory for running any D and B related links
stageConfig.DnBcryptixProvider=Cryptix

# path to evcpassword.properties file for EVC functionality
stageConfig.evcpassword={{ env_vars.stageconfig_evcpassword}}

#crn89085 further settings for DNB

stageConfig.DnB.AddRegistrationURL=https://toolkit.dnb.com/ws/DNB_WebServices.Providers.AddRegistration_V1:wsp_AddRegistration_V1
stageConfig.DnB.ModifyRegistrationURL=https://toolkit.dnb.com/ws/DNB_WebServices.Providers.ModifyRegistration:wsp_ModifyRegistration
stageConfig.DnB.GetRegistrationActivityURL=https://toolkit.dnb.com/ws/DNB_WebServices.Providers.GetRegistrationActivity:wsp_GetRegistrationActivity
