# Holds duration of operating cycle.
# Possible values : YEARLY/QUARTERLY/MONTHLY/WEEKLY
operatingCycleDuration=MONTHLY

# Holds the default base currency code
baseCurrencyCode=EUR

#Class Names for UnMarshalled Agreement Details Object
FRONTER=com.atradius.cabrillo.core.calc.bean.FronterDetails
CAPTIVE=com.atradius.cabrillo.core.calc.bean.CaptiveDetails
COINSURER=com.atradius.cabrillo.core.calc.bean.CoInsuranceDetails
FACULTATIVE=com.atradius.cabrillo.core.calc.bean.FacultativeDetails
RETROEXCESSOFLOSS=com.atradius.cabrillo.core.calc.bean.RetroXLDetails
RETROQUOTASHARE=com.atradius.cabrillo.core.calc.bean.RetroQuotaShareDetails
INTERNALQUOTASHARE=com.atradius.cabrillo.core.calc.bean.IntQuotaShareDetails
EXTERNALQUOTASHARE=com.atradius.cabrillo.core.calc.bean.ExtQuotaShareDetails
EXCESSOFLOSS=com.atradius.cabrillo.core.calc.bean.ExcessOfLossDetails

# Holds the default user name for the batch
defaultUserName={{ vault[app].default_username }}

# Holds non cash booking configurable fields.
statusCode=NEW
actualFlag=A
userJeCategoryName=PROVISION
userJeSourceName=REINS
batchName=REINS
skipFlag=false
skipLastDate=11
