# Holds report root folder
reportFolderPath={{ env_vars.reportfolderpath }}

# Holds report extension type
fileType=csv

#Holds the error folder name
errorFolderName=error

#Holds the business error folder name
businessFolderName=business

#Holds the batch error folder name
batchFolderName=technical

#Holds the warning folder name
warningFolderName=warning
