JNDI_URL=iiop://localhost:{{ env_vars.was_bootstrap_port }}
JNDI_DS_SYMPHONY={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].sym_db_name)) | join(" ") }}
JNDI_DS_REPORTS={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].rep_db_name)) | join(" ") }}

BROKERAPPWS_ENDPOINT={{ env_vars.brokerappws_endpoint }}
FUTURESTATE_ENDPOINT={{ env_vars.futurestate_endpoint }}
