JNDI_URL=iiop://localhost:{{ env_vars.was_bootstrap_port }}
JNDI_DS_SYMPHONY={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].sym_db_name)) | join(" ") }}
JNDI_DS_REPORTS={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].rep_db_name)) | join(" ") }}

BIPSERVICE_ENDPOINT={{ env_vars.bipservice_endpoint }}
FUTURESTATE_ENDPOINT={{ env_vars.futurestate_endpoint }}

#-------------------------- Graydon API Start -------------------------------#
GRAYDON_URL=https://api.graydon.io
GRAYDON_INSIGHTS_URL=https://graydon-insights.com:443
max_times_invoke_monitoringAPI={{ env_vars.max_times_invoke_monitoringapi }}

#-------------------------- Graydon API END -------------------------------#

#-------------------------- CINM drive folders Start -------------------------------#
networkdrive.folder.parent={{ env_vars.networkdrive_folder_parent }}
networkdrive.folder.error=/error
networkdrive.folder.structured=/Structured_Data
networkdrive.folder.unstructured=/Attachments_to_Genesis
networkdrive.folder.originals=/OriginalFiles
networkdrive.folder.originals.error=/error
networkdrive.folder.originals.CouldNotDownloaded=/CouldNotDownloaded
networkdrive.folder.mappings=/Mapping_Files
networkdrive.folder.monitoring=/Monitoring
networkdrive.folder.notices=/Notices
networkdrive.folder.splittedbundle=/SplittedBundle
networkdrive.folder.defaultbatch=Batch_5
networkdrive.folder.batchnames=Batch_5,Batch_6,Batch_4
minimum.threshold.limitofFileDistribution=2000
minthresholddays.toprocessfiles.fromerrorfol=3
Product.Monitoring=Monitoring
Product.Notices=Notices

#Below property will be used for fetching monitoring events
Graydon.StartDate=
Graydon.EndDate=

#---------------------------CINM drive folders End ---------------------------------#

#---------------------------Credentials---------------------------------------------#

############################# ACC ##############################
client_id_be={{ vault[app].client_id_be }}
client_secret_be={{ vault[app].client_secret_be }}

############################# ACC ##############################
client_id_nl={{ vault[app].client_id_nl }}
client_secret_nl={{ vault[app].client_secret_nl }}

############################# ACC ##############################
client_id_uk={{ vault[app].client_id_uk }}
client_secret_uk={{ vault[app].client_secret_uk }}

############################# TST1 ##############################
client_id_backup={{ vault[app].client_id_backup }}
client_secret_backup={{ vault[app].client_secret_backup }}

profile_NL={{ env_vars.profile_nl }}
profile_BE={{ env_vars.profile_be }}
profile_UK={{ env_vars.profile_uk }}
