#### Schema owner of the SQLData Types
dbschema={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].schema_name' | format(vault[app].sym_db_name)) | join(" ") }}

##### Java Class name to the corresponding SQL Data Type ####
##### For example
#####com.ncm.framework.business.BusinessContextSP=CICSPOC_BUSINESS_CONTEXT
com.ncm.extn.data.sp.BalanceSheetInfo=R_XBRL
com.ncm.extn.data.sp.BalanceSheetsTab=XBRL_TABTYPE
com.ncm.extn.data.sp.ChangeCode=R_XBRL_ADJ_CODES
com.ncm.extn.data.sp.ChangeCodesTab=XBRL_TABTYPE_ADJ_CODES
