email=gbwman1@atradius.com
password=
host=intmailrelay.atradiusnet.com
#Interval for the scheduler to run, to be specified in milliseconds
interval=300000
#Property to decide on whether the scheduler is to be started on server start up,
#set to "true" if scheduler is to be started, "false" otherwise
enableScheduler=true
EMAIL_TEMPLATE_FILE=com/atradius/cabrillo/webapp/config/mail_templates.xml
