# Properties file.

#################################  Web Service URL  #################################
URL_WS_ORG={{ env_vars.url_ws_org }}
URL_WS_TH={{ env_vars.url_ws_th }}
URL_ORBS={{ env_vars.url_orbs }}

#################################  Thunderhead properties  #################################
#CREDENTIALS FOR TH
WS_TH_USERID={{ vault[app].wsthuserid }}

#EMPTY PASSWORD STRING IS INTENDED
WS_TH_PASSWORD=
THUSERID={{ vault[app].thuserid }}
THPASSWORD={{ vault[app].thpassword }}
TH_BATCH_PREFIX={{ env_vars.th_batch_prefix }}
TH_BATCH_CONFIG=507000009
TH_SPECIMEN=true
TH_PROJECT_ID=0
TH_JOB_TYPE=0
TH_BATCH_COLLECT=8
THUNDERHEAD_PROVIDER1={{ env_vars.thunderhead_provider1 }}
THUNDERHEAD_PROVIDER2={{ env_vars.thunderhead_provider2 }}
THUNDERHEAD_CONNECTION_FACTORY=jms/RemoteConnectionFactory
THUNDERHEAD_REQUEST_QUEUE=queue/thunderhead/JobRequests

#################################  JNDI properties  #################################
JNDI_URL=iiop://localhost:{{ env_vars.was_bootstrap_port }}
JNDI_OPUS_DS={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].oth_db_name)) | join(" ") }}

#################################  SMTP properties  #################################
SMTP_SERVER_TIMEOUT=300
MAIL_FROM={{ env_vars.mail_from }}
MAIL_TO=schedulingteam@atradius.com;operations@atradius.com
MAIL_SUBJECT=OPUS Status update: SMTP connection restored
MAIL_SESSION=jndi/defaultMail

#################################  Daemon Specific properties  #################################
COPYVIARECIPIENT_ALLOWED=true
APPLICATION_IDS=GID

#################################  Common properties  #################################
#Flag decides if JMS is to be used or not
USE_JMS=true
REVIEWCASE_ALLOWED=true
DATA_SERVICE_TIMEOUT=300
HEALTH_SERVICE_TIMEOUT=300
MAX_NO_OF_RECORDS=10
MAX_NO_OF_THREADS=5
INSTANCE_ID={{ app_host_vars[app].instance_id }}
DEBUG_PATH={{ env_vars.debug_path }}
DP_OUTPUT_FILEPATH={{ env_vars.dp_output_filepath }}
SIGN_URL1=/WEB-INF/config/application/singleSignStructure.xml
SIGN_URL2=/WEB-INF/config/application/doubleSignStructure.xml
