# The contents of this property file can be reloaded via index.jsp
# Author Nikhil , EVC project

genesis.user={{ vault[app].genesis_user }}
genesis.password={{ vault[app].genesis_password }}
genesis.Document_Class=BUINF
# All genesis Indexes should start with genesis.index ,code will automatically pick them up
genesis.index.Capture_Location=CRDIFF
genesis.index.Document_File_Type=BUINF
genesis.index.Document_Type=101A
genesis.index.Format_Type=ACROB
genesis.index.Security=N

# General messages
bip.reportdisplay.notavailable = Report not Available
bip.evc.validationerror=PC

# EVC Properties
bip.evc.report.countryCode=DE
bip.evc.report.legitimate_interest=LEIN-100
bip.evc.search.searchtype=SETY-1
bip.evc.search.registertype=RETY
bip.evc.MaxNumberSearchHits=40
bip.evc.RequestTimeout=360000
bip.evc.logon.keylist.message = The keylist version at EVC is different
bip.evc.preferred.language={{ env_vars.bip_evc_preferred_language }}
bip.evc.searchheader.transactionreference={{ env_vars.bip_evc_searchheader_transactionreference }}

# Properties for checkMonitoringStatus
bip.evc.maxresults=500
bip.evc.checkMonitoringStatus.CMOF.InclstdMonitoringExt=false
bip.evc.checkMonitoringStatus.CMOF.InclExtMonOrder=false
bip.evc.checkMonitoringStatus.InclstdMonitoringExt=true
bip.evc.checkMonitoringStatus.InclExtMonOrder=true
bip.evc.checkMonitoringStatus.InclExtMonPlsOrder={{ env_vars.bip_evc_checkmonitoringstatus_inclextmonplsorder }}
bip.evc.checkMonitoringStatus.InclExtMonPlsActive={{ env_vars.bip_evc_checkmonitoringstatus_inclextmonplsactive }}
bip.evc.checkMonitoringStatus.InclExtMonActive=true
#Properties for Change Extended Monitoring
bip.evc.changeExtendedMonitoring.ExtendedMonitoringPlus=false
#Properties Report Type or product type,this is only used for comparision
bip.evc.checkMonitoringStatus.MOA.productType=PRTY-1002
bip.evc.requestOnlineReport.CR.productType=PRTY-3
bip.evc.orderrequest.BR.productType=PRTY-2
bip.evc.CMON.MaxDate=31-12-4712
bip.evc.CMOF.Extendedmonitoringplus=false
bip.evc.EVCReportMapper.updatenote.retcode=NU
bip.evc.checkMonitoringStatus.SplerrorCode=ER-9
bip.evc.constantmonitoring.requestDelayedOnlineReports=false

#EVC Header information mrf48885 update keylistversion
bip.evc.requestheader.Communicationlanguage={{ env_vars.bip_evc_requestheader_communicationlanguage }}
bip.evc.requestheader.clientapplicationversion=100
bip.evc.requestheader.clientapplicationname={{ env_vars.bip_evc_requestheader_clientapplicationname }}
bip.evc.requestheader.keylistversion=38
bip.evc.requestheader.transactionreference=Atradius

# Added entry for MailBoxDirectoryRead

bip.evc.MailBoxDirectory.Numberofentries=500
bip.evc.MailBoxDirectory.Deliverytypereport=true
bip.evc.MailBoxDirectory.Deliverytypestatusreply=true
bip.evc.MailBoxDirectory.Deliverytypestockdelivery=false
bip.evc.MailBoxDirectory.Deliverytypesupplement=true
bip.evc.MailBoxDirectory.Deliverytypeupdate=true
bip.evc.MailBoxDirectory.Entriesread=false
bip.evc.MailBoxDirectory.Entriesunread=true
bip.evc.MailBoxDirectory.Identificationnumber=
bip.evc.MailBoxDirectory.Openorders=false
bip.evc.MailBoxDirectory.Pagereference=
bip.evc.MailBoxDirectory.Referencenumber=
bip.evc.MailBoxDirectory.Callperiod.Dateend=
bip.evc.MailBoxDirectory.Callperiod.Datestart=
bip.evc.MailBoxDirectory.Creationperiod.Dateend=
bip.evc.MailBoxDirectory.Creationperiod.Datestart=
bip.evc.MailBoxDirectory.Orderperiod.Dateend=
bip.evc.MailBoxDirectory.Orderperiod.Datestart=

# For Order (Inquiry)
bip.evc.orderrequest.orderType=ORTY-1

BUSINESS_LOG_FOLDER=DEU_125
bip.evc.search.registertypeA=RETY-DE-1
bip.evc.search.registertypeB=RETY-DE-2
bip.evc.search.registertypeP=RETY-DE-3
bip.evc.search.registertypeC=RETY-DE-4
bip.evc.search.registertypeV=RETY-DE-5
bip.evc.search.registertypeRETYA=A
bip.evc.search.registertypeRETYB=B
bip.evc.search.registertypeRETYP=P
bip.evc.search.registertypeRETYC=C
bip.evc.search.registertypeRETYV=V

# CINM drive folders
networkdrive.folder.originals={{ env_vars.networkdrive_folder_originals }}

# mrf48162
############ DMS URL PROPERTY IN SYMG #################
dmsservice.store.url={{ env_vars.dmsservice_store_url }}

############ OIDM PROPERTIES IN SYMG #################
oidm.get_token.environment={{ env_vars.oidm_get_token_environment }}
oidm.get_token.url={{ env_vars.oidm_get_token_url }}
oidm.get_token.basic_auth={{ vault[app].oidm_get_token_basic_auth }}
oidm.get_token.scope={{ env_vars.oidm_get_token_scope }}
oidm.get_token.domain={{ env_vars.oidm_get_token_domain }}

################### OIDM Token Flag IN SYMW,SYMF,SYMG,SYMP ###################
########## POSSIBLE VALUES : Y/N ############################
oidm.get_token.flag=Y
############ BELOW PROPERTIES WILL BE COMMON ACROSS ALL ENVIRONMENTS #################
############ DMS SERVICE PROPERTIES IN SYMW,SYMF,SYMG,SYMP #################
dmsservice.header.application=BIP
dmsservice.header.invocationservice=http://atradius.com/bip/documents
dmsservice.header.correlationid=bip123
dmsservice.header.msgid=bip456

#Time in miliseconds. 3000000 ms - > 50 minutes
oidm.get_token.timer=3000000
