stageconfig.datafile=/home/webadmn/bip
stageConfig.log4jConfig=
stageConfig.serviceEndpoint={{ env_vars.stageconfig_serviceendpoint }}
stageConfig.evcSearchURL={{ env_vars.stageconfig_evcsearchurl }}
stageConfig.evcURL={{ env_vars.stageconfig_evcurl }}
stageConfig.bipproperties={{ env_vars.stageconfig_bipproperties }}
stageConfig.evcDirectory=/BIPMONITORINGLOADS/EVC/transit
stageConfig.evcpassword={{ env_vars.stageconfig_evcpassword }}
