---
- name: Assert that app is standalone
  run_once: true
  ansible.builtin.assert:
    that:
      - "env_vars.dmgr_host is not defined"
    fail_msg: "app={{ app }} - Application {{ env_vars.app_name }} is not standalone"
    success_msg: "app={{ app }} - Application {{ env_vars.app_name }} is standalone"

- name: Output application and host level variables
  ansible.builtin.debug:
    msg: "app_name - {{ env_vars.app_name }}, profile_name - {{ env_vars.profile_name }}, server_name - {{ env_vars.server_name }}, was_path - {{ was_path }}"

- name: Set service_name
  ansible.builtin.set_fact:
    service_name: "was_{{ env_code | lower }}{{ app_vars.common_app_group | default(app | lower) }}.service"

- name: Check service status
  ansible.builtin.service_facts:

- name: Output service status
  ansible.builtin.debug:
    var: ansible_facts.services[service_name]
  failed_when: ansible_facts.services[service_name].state == "running"

- name: Check if processes are running (full command)
  ansible.builtin.shell: "set -o pipefail && ps -fu webadmn \
   | grep java | grep -v grep | egrep -E -- '{{ env_vars.profile_name }}'"  # noqa no-changed-when
  register: command_processes
  failed_when: false
  changed_when: command_processes.stdout_lines | length > 0

- name: Check if processes are running (get PIDs)
  ansible.builtin.shell: "set -o pipefail && ps -fu webadmn \
   | grep java | grep -v grep | egrep -E -- '{{ env_vars.profile_name }}' | awk {'print $2'}"  # noqa no-changed-when
  register: running_processes
  failed_when: false
  changed_when: running_processes.stdout_lines | length > 0

- name: Print process ID
  ansible.builtin.debug:
    msg: "Process already running PID '{{ running_processes.stdout_lines }}'"
  failed_when: true
  when: running_processes.stdout_lines | length > 0

- name: Start service
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: started
  when: ansible_facts.services[service_name].state != "running"
  async: 1200 # wait for up to 20 mins, poll every 10 sec
  poll: 10
