---
galaxy_info:
  author: Daniel Pitt (@DJPITT92)
  description: Install OpenJDK Java Development Kit
  company: Atradius

  license: proprietary

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - java
    - openjdk
    - jdk
    - development
