#############           JBOSS JMS CONFIGURATIONS                #############
PROVIDER1={{ env_vars.provider1 }}
PROVIDER2={{ env_vars.provider2 }}
CONNECTION_FACTORY=jms/RemoteConnectionFactory
DESTINATION=queue/thunderhead/Responses

#############           THUNDERHEAD CONFIGURATIONS              #############
URL_WS_TH={{ env_vars.url_ws_th }}
WS_TH_USERID={{ vault[app].ws_th_userid }}
WS_TH_PASSWORD=
THUSERID={{ vault[app].thuserid }}
THPASSWORD={{ vault[app].thpassword }}

#############           OTHER CONFIGURATIONS                    #############
AUTO_START=true
DEBUG=false
SER_FILEPATH={{ was_path }}/profiles/{{ env_vars.profile_name }}/logs/{{ env_vars.server_name }}
CONSUMERS=20
ENV={{ env_vars.env }}
JNDI_EMAIL_SESSION_NAME=jndi/defaultMail

#############           HIBERNATE CONFIGURATIONS        #############
JNDI_URL=iiop://localhost:{{ env_vars.was_bootstrap_port}}
JNDI_OPUS_DS={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].sym_db_name)) | join(" ") }}
#don't change below until requested
JNDI_CLASS=com.ibm.websphere.naming.WsnInitialContextFactory
DRIVER_CLASS=oracle.jdbc.driver.OracleDriver
DIALECT_CLASS=org.hibernate.dialect.Oracle10gDialect
POOL_SIZE=0
CACHE_PROVIDER=org.hibernate.cache.NoCacheProvider
SHOW_SQL=false
FORMAT_SQL=false
SQL_COMMENTS=false
