CSV_INPUT_FILE_LOCATION={{ env_vars.csv_input_file_location }}
CSV_INPUT_FILE_NAME=HCM_Dump.csv

database.jndi-name={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].sym_db_name)) | join(" ") }}
mail.jndi-name=mail/Default

#Email updated - CHG0073885
mail.toEmailId=hr_invalid_hcm_extract_records@atradius.com
mail.fromEmailId=noreply@atradius.com

mail.fromUserName=NoReply

LDAP_PATH_PRINCIPAL={{ env_vars.ldap_path_principal }}
LDAP_PATH_INITIAL={{ env_vars.ldap_path_initial }}

LDAP_PROVIDER_URL={{ env_vars.ldap_provider_url }}
LDAP_PASSWORD={{ vault[app].ldap_password }}

#MRF551269
mail.env={{ env_vars.mail_env}}
