# Properties file.

#################################  Web Service URL  #################################
URL_WS_ORG={{ env_vars.url_ws_org }}
URL_WS_TH={{ env_vars.url_ws_th }}
URL_ORBS={{ env_vars.url_orbs }}

URL_WS_CLD={{ env_vars.url_ws_cld }}
URL_WS_INVOICE={{ env_vars.url_ws_invoice }}
URL_WS_POLICY={{ env_vars.url_ws_policy }}
URL_WS_DECLARATION={{ env_vars.url_ws_declaration }}
URL_WS_CLEAR={{ env_vars.url_ws_clear }}
URL_WS_COMPOSITE_SERVICE={{ env_vars.url_ws_composite_service }}

URL_SCORE_AUTH={{ env_vars.url_score_auth }}
SCORE_CLIENT_ID={{ vault[app].score_client_id }}
SCORE_CLIENT_SECRET={{ vault[app].score_client_secret }}
SCORE_SCOPE={{ env_vars.score_scope }}
SCORE_GRANT_TYPE=client_credentials
URL_SCORE_API={{ env_vars.url_score_api }}

#################################  Thunderhead properties  #################################
#CREDENTIALS FOR TH
WS_TH_USERID=DATAPROCESSING
#EMPTY PASSWORD STRING IS INTENDED
WS_TH_PASSWORD=
THUSERID={{ vault[app].th_userid }}
THPASSWORD={{ vault[app].th_password }}

TH_BATCH_PREFIX={{ env_vars.th_batch_prefix }}
TH_BATCH_CONFIG=507000009
TH_SPECIMEN={{ env_vars.th_specimen }}
TH_PROJECT_ID=0
TH_JOB_TYPE=0
TH_BATCH_COLLECT=8

THUNDERHEAD_PROVIDER1={{ env_vars.thunderhead_provider1 }}
THUNDERHEAD_PROVIDER2={{ env_vars.thunderhead_provider2 }}
THUNDERHEAD_CONNECTION_FACTORY=jms/RemoteConnectionFactory
THUNDERHEAD_REQUEST_QUEUE=queue/thunderhead/JobRequests


#################################  JNDI properties  #################################
JNDI_URL=iiop://localhost:{{ env_vars.was_bootstrap_port }}
JNDI_OPUS_DS={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].oth_db_name)) | join(" ") }}


#################################  SMTP properties  #################################
SMTP_SERVER_TIMEOUT=300
MAIL_FROM={{ env_vars.mail_from }}
MAIL_TO=schedulingteam@atradius.com;operations@atradius.com;
MAIL_SUBJECT=OPUS Status update: SMTP connection restored
MAIL_SESSION=jndi/defaultMail


#################################  Daemon Specific properties  #################################
COPYVIARECIPIENT_ALLOWED=true
TOPCALL_ENABLING=true

#CREDENTIALS FOR SCORE
WS_SCORE_USERID={{ vault[app].score_userid }}
WS_SCORE_PASSWORD={{ vault[app].score_password }}

# To be maintained for type 39 Collections invoices
# Fix for defect 5492
# Countries where VAT is not applicable are currently Australia, Singapore, HongKong, USA
# Countries where EU Flag must be False are Australia, Singapore, HongKong, USA, Canada, UK, Mexico
COLLECTIONS_NON_VAT_PAYEE=15951070,16979901,16981761,15258332

#Composite Web Service
USE_AGGREGATE_SERVICE=true
USE_REVIEW_CASE_VARIABLES=true
GREEK_INVOICE={{ env_vars.greek_invoice }}
CONVERT_RUSSIAN_AMOUNT=true
COMPOSITE_TOKEN={{ env_vars.composite_token }}
COMPOSITE_TIME_OUT={{ env_vars.composite_token_timeout }}

#Italian invoicing types
ITALIAN_INVOICE_TYPE=1,2,3,6,7,10,11,12,15,16,17,18,19
#Italian ORNON_ID
ITALIAN_INV_ORNON_ID=18,31
#AIS NCM IDs
AIS_NCM_ID=312,712
#ACYC NCM IDs
ACYC_NCM_ID=12,812,912
#Italian e invoice date
EINVOICE_YEAR=2019
EINVOICE_MONTH=1
EINVOICE_DATE=1

APPLICATION_IDS=IVB,IVI,INV,INI,INB

#################################  Common properties  #################################
#Flag decides if JMS is to be used or not
USE_JMS=true
REVIEWCASE_ALLOWED=true
DATA_SERVICE_TIMEOUT=300
HEALTH_SERVICE_TIMEOUT=300
MAX_NO_OF_RECORDS={{ env_vars.max_no_of_records }}
MAX_NO_OF_THREADS={{ env_vars.max_no_of_threads }}
INSTANCE_ID={{ app_host_vars[app].instance_id }}

DEBUG_PATH={{ env_vars.debug_path }}
DP_OUTPUT_FILEPATH={{ env_vars.dp_output_filepath }}


#Italian invoice storing location for AIS
ITALIAN_DP_AIS_OUTPUT_FILEPATH={{ env_vars.italian_dp_ais_output_filepath }}
#Italian invoice storing location for ACYC
ITALIAN_DP_ACYC_OUTPUT_FILEPATH={{ env_vars.italian_dp_acyc_output_filepath }}

BOND_OUTPUT_FILEPATH={{ env_vars.bond_output_filepath }}

################################# Authentication API properties #################################
OAUTH_TOKEN_URL={{ env_vars.oauth_token_url }}
CLIENT_ID={{ vault[app].oauth_client_id }}
CLIENT_SECRET={{ vault[app].oauth_client_secret }}
SCOPE={{ env_vars.oauth_scope }}
IDENTITY_DOMAIN={{ env_vars.oauth_identity_domain }}

################################# CIBT/Shared Service properties #################################
ATR_ORIGIN_USER_ID={{ vault[app].atr_origin_user_id }}
ATR_ORIGIN_APPLICATION={{ env_vars.atr_origin_application }}
ATR_ORIGIN_SERVICE={{ env_vars.atr_origin_service }}
ATR_INVOKE_SERVICE={{ env_vars.atr_invoke_service }}

CIBT_CASH_TRANS_URL={{ env_vars.cibt_cash_trans_url }}
CIBT_SEARCH_CASH_TRANS_URL={{ env_vars.cibt_search_cash_trans_url }}
CIBT_POLICY_FOR_INVOICING={{ env_vars.cibt_policy_for_invoicing }}
CIBT_OFFER_POLICY_DATA_VALUE={{ env_vars.cibt_offer_policy_data_value }}

#MRF50971
SC_CURRENCY_FX_URL={{ env_vars.sc_currency_fx_url }}
