# Properties file.
partnerCode=CYC
historicSystemCode=CYC_POL
startDate=01.01.2009
endDate=31.12.2099
maxDate=31.12.4712
insurancePeriodValue=90
estimatedAnnualTurnover=1
estimatedExportPercentage=50
insuredMaxLiabilityAmt=999999999
setPrice=50.00
setThresholdAmt=100.00
paymentCondition=paymentCondition
paymentTerms=paymentTerms
tradeSectorDescription=derived from trade sector delivered by CyC
mailboxId = 20012

# symz - ESUCA01,ESUCA02,ESUCA03,ESUCA04,ESUCA05,ESJ52D2
mailboxUserId = {{ vault[app].mailbox_userid }}

accessInd = U
statusCodeLive=LIVE
statusCodeCanc=CANC
statusChangeCode=OTHR
systemDate=sysdate
# the other system organisation code has been modified from CYC to CY to allow for 
# Portuguese organisations 
otherSysOrganisationCY=CY
otherSysOrganisationCYC=CYC
idType=EXTID
variableCode=POLTRS
# EA_TRANS_LOG_SP
streamKey=1
sortKey=1
locationCode=GL
thmCode=BUBD093T
priority=B
productType = MAPC
productClass = CINS
# Declarations
firstReminderFlag=N
secondReminderFlag =N
declarationDueInd=D        
noDeclarationRecFlag=N
# Policy Dets
premiumPrincipleInd=N
auAllowedInd=A
auApplyCustRatingInd=N
auAslScalingPct=100
auPrelimDecisionFlag=N
auAllowCilcFlag=Y
credlimMonitorInd=RE
auAllowDecisionInd=R
# functions
newPolicy=N
updateOrTransferPolicy=U
exchangePolicy=E
cancelPolicy=C
sl_ind = 3
defaultCountry=ESP

# Changes done for CyC Brazil CoE Phase 2 by inrran1 on Date 20-08-2013
defaultCurrency=EUR
