---
galaxy_info:
  author: Daniel Benitez Aguila (@ESDBEN2)
  description: Configure Linux systemd services for WebSphere Application Server profiles and servers
  company: Atradius

  license: proprietary

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - websphere
    - linux
    - systemd
    - service
    - automation
