---
galaxy_info:
  author: Manbir Singh (@GBMSINGH)
  description: Create WebSphere Application Server standalone profile
  company: Atradius

  license: proprietary

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - websphere
    - profile
    - standalone
    - appserver
