
#################    Encryption key ##################
############  EDWD,EDWG,EDWP ###################
KEY1={{ vault[app].ldap_key1 }}
KEY2={{ vault[app].ldap_key2 }}

################ LDAP SERVER connection details ############
############  EDWD,EDWG,EDWP ###################

JAVA_NAMING_FACTORY_INITIAL = com.sun.jndi.ldap.LdapCtxFactory
JAVA_NAMING_PROVIDER_URL =ldap://gbcdf-ldap.atradiusnet.com:389
JAVA_NAMING_SECURITY_AUTHENTICATION = simple
BIND_DN =CN=SVC_SolvencyII,OU=Service Accounts,OU=AD,DC=atradiusnet,DC=com
BINDCREDENTIAL = {{ vault[app].ldap_bindcredential }}
BASE_CTX_DN = DC=atradiusnet,DC=com
JAVA_NAMING_REFERRAL =follow

