################# This variable depends on the environment ##################

CURR_ENVIRONMENT={{ env_vars.mail_curr_environment }}

################# EDWD,EDWG,EDWP ##################
##### BELOW PROPERTIES WILL BE SAME IN ALL ENVIRONMENTS ######

#MAIL SWITCH FLAG
MAIL_SWTICH_FLAG=True 

#FROM EMAIL
FROM_EMAIL=nobody@gl04.atradius.com

#MAIL SUBJECT
MAIL_SUBJECT=Reference Data status changed to -

#EMAIL VALIDATION REGEX PATTERN
EMAIL_PATTERN =^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$
