JNDI_URL=iiop://localhost:{{ env_vars.was_bootstrap_port }}
JNDI_DS_SYMPHONY={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].sym_db_name)) | join(" ") }}
JNDI_DS_REPORTS={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].rep_db_name)) | join(" ") }}

CERVED_ENDPOINT=https://wscerved.cerved.com/WSCerved/wscerved
FUTURESTATE_ENDPOINT={{ env_vars.futurestate_endpoint }}
CERVED_USER_ID={{ vault[app].cerved_user_id }}
CERVED_PASSWORD={{ vault[app].cerved_password }}
GENESIS_USERID={{ vault[app].genesis_userid }}
GENESIS_PASSWORD={{ vault[app].genesis_password }}
# Genesis Document Properties
genesis_Document_Class={{ env_vars.genesis_document_class }}
genesis_index_Capture_Location=CRDIFF
genesis_index_Document_File_Type=BUINF
genesis_index_Document_Type={{ env_vars.genesis_index_document_type }}
genesis_index_Format_Type=ACROB
genesis_index_Security=N
genesis_index_Document_Monitoring_Type=113A

#MRF47525
#SFTP properties
cervedFTPServer={{ env_vars.cerved_ftp_server }}
cervedFTPPort={{ env_vars.cerved_ftp_port }}
cervedFTPUser={{ vault[app].cerved_ftp_user }}
cervedFTPPassword={{ vault[app].cerved_ftp_password}}
cervedCRPUFolder={{ env_vars.cerved_crpu_folder }}
cervedCRPUNoticesFTPFolder={{ env_vars.cerved_crpu_notices_ftp_folder }}

BIPSERVICE_ENDPOINT={{ env_vars.bipservice_endpoint }}
MAX_PROCESS_RECORDS=1001
MAX_PROCESS_ITERATIONS=16

cervedParentFolder={{ env_vars.cerved_parent_folder }}
cervedCRPUOriginalFolder={{ env_vars.cerved_crpu_original_folder }}
cervedCRPUNoticesOriginalFolder={{ env_vars.cerved_crpu_notices_original_folder }}
cervedCRPUStrucFolder={{ env_vars.cerved_crpu_struc_folder }}
cervedCRPUNoticesStrucFolder={{ env_vars.cerved_crpu_notices_struc_folder }}
cervedCRPUPdfFolder={{ env_vars.cerved_crpu_pdf_folder }}
cervedCRPUNoticesPdfFolder={{ env_vars.cerved_crpu_notices_pdf_folder }}
cervedErrorFolder=/error
cervedStructuredFolder=/Structured_Data
cervedGenesisFolder=/Attachments_to_Genesis
cervedOriginalFolder=/OriginalFiles
cervedMappingFolder=/Mapping_Files
cervedCRPUFolder1=/CRPU
cervedNoticesFolder1=/CRPU-NOTICES

############ GENESIS PROPERTIES #################
documentservice.genesis.user={{ env_vars.documentservice_genesis_user }}
documentservice.genesis.security=N
documentservice.genesis.capturelocation=CRDIFF
documentservice.genesis.document_file_type=BUINF
documentservice.genesis.document_class=BUINF
documentservice.genesis.gsdtetype=101A

############ DMS URL PROPERTY #################
dmsservice.store.url={{ env_vars.dmsservice_store_url }}

############ OIDM PROPERTIES #################
oidm.get_token.environment={{ env_vars.oidm_get_token_environment }}
oidm.get_token.url={{ env_vars.oidm_get_token_url }}
oidm.get_token.basic_auth={{ vault[app].oidm_get_token_basic_auth }}
oidm.get_token.scope={{ env_vars.oidm_get_token_scope }}
oidm.get_token.domain={{ env_vars.oidm_get_token_domain }}

############ DMS SERVICE PROPERTIES IN SYMW,SYMF,SYMG,SYMP #################
dmsservice.header.application=BIP
dmsservice.header.invocationservice=http://atradius.com/bip/documents
dmsservice.header.correlationid=bip123
dmsservice.header.msgid=bip456

#Time in miliseconds. 3000000 ms - > 50 minutes
oidm.get_token.timer=3000000

#Maximum size of attached file
mail.file.size=85
