JNDI_URL=iiop://localhost:{{ env_vars.was_bootstrap_port }}
JNDI_DS_SYMPHONY={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].sym_db_name)) | join(" ") }}
JNDI_DS_REPORTS={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].rep_db_name)) | join(" ") }}

BIPSERVICE_ENDPOINT={{ env_vars.bipservice_endpoint }}
FUTURESTATE_ENDPOINT={{ env_vars.futurestate_endpoint }}

MAX_PROCESS_RECORDS=
MAX_PROCESS_ITERATIONS=

DnBCharSet=ISO-8859-1
datafile=
proxyHost=
proxyPort=

DnBUser={{ vault[app].dnb_user }}
DnBPassword={{ vault[app].dnb_password }}

#------------------------------------------- Search and Online operation - Not Active as of now -------------------------------------------------#
DnBMaxNumberSearchHits=50
DnBURL=https://toolkit-api.dnb.com/ws/DNB_WebServices.Providers.OrderAndInvestigations.GDP_V3:wsp_GDP_V3
DnBSearchURL=https://toolkit-api.dnb.com/ws/DNB_WebServices.Providers.LookUp:wsp_LookUp
DnB.BIRURL=https://toolkit-api.dnb.com/ws/DNB_WebServices.Providers.OrderAndInvestigations.OtherProducts.BIR_V1:wsp_BIR_V1
#------------------------------------------- Search and Online operation - Not Active as of now -------------------------------------------------#


#------------------------------------------- Switzerland ----------------------------------------------------------------------------------------#
DnBUser14371663={{ vault[app].dnb_user_14371663 }}
DnBPassword14371663={{ vault[app].dnb_password_14371663 }}
#------------------------------------------- Switzerland ----------------------------------------------------------------------------------------#

#------------------------------------------- D&B Global ----------------------------------------------------------------------------------------#
DnBUser880={{ vault[app].dnb_user_880 }}
DnBPassword880={{ vault[app].dnb_password_880 }}
#------------------------------------------- D&B Global ----------------------------------------------------------------------------------------#

#------------------------------------------- Australia ----------------------------------------------------------------------------------------#
DnBUser11517859={{ vault[app].dnb_user_11517859 }}
DnBPassword11517859={{ vault[app].dnb_password_11517859 }}
#------------------------------------------- Australia ----------------------------------------------------------------------------------------#

#------------------------------------------- Canada ----------------------------------------------------------------------------------------#
DnBUser14625239={{ vault[app].dnb_user_14625239 }}
DnBPassword14625239={{ vault[app].dnb_password_14625239 }}
#------------------------------------------- Canada ----------------------------------------------------------------------------------------#

#------------------------------------------- USA ----------------------------------------------------------------------------------------#
DnBUser4882884={{ vault[app].dnb_user_4882884 }}
DnBPassword4882884={{ vault[app].dnb_password_4882884 }}
#------------------------------------------- USA ----------------------------------------------------------------------------------------#

#------------------------------------------- Poland ----------------------------------------------------------------------------------------#
DnBUser22428684={{ vault[app].dnb_user_22428684 }}
DnBPassword22428684={{ vault[app].dnb_password_22428684 }}
#------------------------------------------- Poland ----------------------------------------------------------------------------------------#

#------------------------------------------- DNB Monitoring changes Starts ----------------------------------------------------------------#
DnB.AddRegistrationURL=https://toolkit-api.dnb.com/ws/DNB_WebServices.Providers.AddRegistration_V1:wsp_AddRegistration_V1
DnB.ModifyRegistrationURL=https://toolkit-api.dnb.com/ws/DNB_WebServices.Providers.ModifyRegistration:wsp_ModifyRegistration
DnB.GetRegistrationActivityURL=https://toolkit-api.dnb.com/ws/DNB_WebServices.Providers.GetRegistrationActivity:wsp_GetRegistrationActivity
DnB.EUPVURL=https://toolkit-api.dnb.com/ws/DNB_WebServices.Providers.OrderAndInvestigations.PanEuropean_V4:wsp_PanEuropean_V4
DnB.WBMIURL=https://toolkit-api.dnb.com/ws/DNB_WebServices.Providers.OrderAndInvestigations.WorldBase_V4:wsp_WorldBase_V4
DnB.GetNotificationsURL=https://toolkit-api.dnb.com/ws/DNB_WebServices.Providers.GetNotifications_V8:wsp_GetNotifications_V8
DnB.GetRegiListDownloadURL=https://toolkit-api.dnb.com/ws/DNB_WebServices.Providers.GetRegistrationList_V1:wsp_GetRegistrationList_V1

DnB.StartDate=
DnB.EndDate=
DnB.RegistrationActivity_StartDate=
DnB.RegistrationActivity_EndDate=
#------------------------------------------- DNB Monitoring changes End ----------------------------------------------------------------#

# Report - Product type mapping
DnB.OnlineReport.Product.Mapping=D and B Business Information Report-BIR,Business Verification-GDP,Comprehensive Report-GDP,Decision Support-GDP,Enterprise Management-GDP,European Preview-EUPV,Financial Standing-GDP,WorldBase Marketing ID-WBMI,Quick Check-GDP,Vendor Management-GDP,Premium Report-GDP,Global Failure Risk Score-GDP,Delinquency Score-GDP

#------------------------------------------- CINM drive folders Start ----------------------------------------------------------------#

networkdrive.folder.monitoring=/Monitoring
networkdrive.folder.notices=/Notices
networkdrive.folder.splittedbundle=/SplittedBundle
networkdrive.folder.mappings=/Mapping_Files
networkdrive.folder.parent={{ env_vars.networkdrive_folder_parent }}
networkdrive.folder.error=/error
networkdrive.folder.structured=/Structured_Data
networkdrive.folder.unstructured=/Attachments_to_Genesis
networkdrive.folder.originals=/OriginalFiles
networkdrive.folder.RegListFiles=/RegListFiles
bip.faliure.email={{ env_vars.bip_faliure_email }}

#------------------------------------------- CINM drive folders End ----------------------------------------------------------------#

Product.Monitoring=Monitoring
Product.Notices=Notices

mail.outgoing.serverHost=
mail.outgoing.serverPort=
mail.outgoing.user=
mail.outgoing.password=

# * -------------------------------------------------------------------
# The below property will be used in various BIP-USA components
# to avoid clashes with the Cryptix Encryption library...
# This property value is mandatory for running any D and B related links
DnBcryptixProvider=Cryptix

######################## DnB Monitoring ########################################
bip.dnb.RequestTimeout=360000
bip.dnb.AddRegistration.Customer_Account_ID=
bip.dnb.AddRegistration.Endorsement=
bip.dnb.AddRegistration.Expiration_Date=
bip.dnb.AddRegistration.Reason_Code=
bip.dnb.AddRegistration.Do_not_Renew=N
bip.dnb.AddRegistration.Trade_up_Indicator=True

bip.dnb.GetRegistrationActivity.Customer_Account_ID=
bip.dnb.GetRegistrationActivity.Endorsement=
bip.dnb.GetRegistrationActivity.Activity_Codes=
bip.dnb.GetRegistrationActivity.Pending_Activity_only=
bip.dnb.GetRegistrationActivity.User_Level=
bip.dnb.GetRegistrationActivity.Result_Ticket=
bip.dnb.GetRegistrationActivity.Activity_Date_From=
bip.dnb.GetRegistrationActivity.Activity_Date_To=
bip.dnb.GetRegistrationActivity.Renewal_Date_From=
bip.dnb.GetRegistrationActivity.Renewal_Date_To=
bip.dnb.GetRegistrationActivity.Expiration_Date_From=
bip.dnb.GetRegistrationActivity.Expiration_Date_To=
bip.dnb.GetRegistrationActivity.Character_Set_Override=

bip.dnb.ModifyRegistration.Customer_Account_ID=
bip.dnb.ModifyRegistration.New_Account_ID=
bip.dnb.ModifyRegistration.Customer_Endorsement=
bip.dnb.ModifyRegistration.New_Endorsement=
bip.dnb.ModifyRegistration.Cancel_Registration=
bip.dnb.ModifyRegistration.Un-cancel_Registration=
bip.dnb.ModifyRegistration.Renew_Registration=
bip.dnb.ModifyRegistration.Do_not_Renew_Registration=N
bip.dnb.ModifyRegistration.Character_Set_Override=
bip.dnb.ModifyRegistration.Expiration_Date=

bip.dnb.GetNotifications.DnB_DUNS_Number=
bip.dnb.GetNotifications.CountryCode=
bip.dnb.GetNotifications.Product_Name=
bip.dnb.GetNotifications.Notification_Level=
bip.dnb.GetNotifications.Endorsement=
bip.dnb.GetNotifications.User_Level=
bip.dnb.GetNotifications.Detection_Date_From=
bip.dnb.GetNotifications.Detection_Date_To=
bip.dnb.GetNotifications.Received_Date_From=
bip.dnb.GetNotifications.Received_Date_To=
bip.dnb.GetNotifications.Active_Registrations_only=False
bip.dnb.GetNotifications.Pending_Notices_only=False
bip.dnb.GetNotifications.Do_not_Mark_as_Read=True
bip.dnb.GetNotifications.Character_Set_Override=

bip.dnb.GetRegistrationList.RequestTimeout=360000
bip.dnb.GetRegistrationList.DnB_DUNS_Number=
bip.dnb.GetRegistrationList.CountryCode=
bip.dnb.GetRegistrationList.Product_Name=
bip.dnb.GetRegistrationList.Notification_Level=
bip.dnb.GetRegistrationList.Customer_Account_ID=
bip.dnb.GetRegistrationList.Endorsement=
bip.dnb.GetRegistrationList.User_Level=
bip.dnb.GetRegistrationList.Result_Ticket=
bip.dnb.GetRegistrationList.Last_Update_Date_From=
bip.dnb.GetRegistrationList.Last_Update_Date_To=
bip.dnb.GetRegistrationList.Renewal_Date_From=
bip.dnb.GetRegistrationList.Renewal_Date_To=
bip.dnb.GetRegistrationList.Expiration_Date_From=
bip.dnb.GetRegistrationList.Expiration_Date_To=
bip.dnb.GetRegistrationList.Character_Set_Override=

#######  BIP.DNB.COUNTRYLIST  PROPERTY IN SYMW,SYMF,SYMG ,SYMP  ##########
bip.dnb.countrylist=840,USA;554,NZL;036,AUS;380,SMR;756,CHE;438,LIE;484,MEX;124,CAN;792,TUR;344,HKG;076,BRA;392,JPN;442,LUX;398,KAZ;012,DZA;788,TUN;702,SGP;796,TCA;643,RUS;158,TWN;410,KOR;458,MYS;764,THA;196,CYP;440,LTU;032,ARG;428,LVA;740,SUR;152,CHL;328,GUY;233,EST;170,COL;360,IDN;470,MLT;804,UKR;862,VEN;608,PHL;604,PER;840,PRI;332,HTI;214,DOM;704,VNM;188,CRI;320,GTM;218,ECU;591,PAN;858,URY;092,VGB;340,HND;050,BGD;780,TTO;222,SLV;659,KNA;388,JAM;292,GIB;112,BLR;662,LCA;498,MDA;840,VIR;268,GEO;558,NIC;504,MAR;072,BWA;710,ZAF;376,ISR;446,MAC;516,NAM;288,GHA;404,KEN;426,LSO;508,MOZ;748,SWZ;834,TZA;716,ZWE;768,TGO;533,ABW;531,CUW;534,SXM;060,BMU;818,EGY;096,BRN;616,POL;480,MUS;894,ZMB;566,NGA;584,MHL;242,FJI;068,BOL;760,SYR;024,AGO;156,CHN;178,COG;300,GRC;028,ATG;044,BHS;084,BLZ;052,BRB;800,UGA;660,AIA;882,WSM;116,KHM;670,VCT;308,GRD;136,CYM;212,DMA;682,SAU;454,MWI;500,MSR;580,MNP;583,FSM;184,COK;762,TJK;784,ARE