# application_config.properties 
URL_WS_ORG={{ env_vars.url_ws_org }}
URL_WS_CLD={{ env_vars.url_ws_cld }}

ORG_SERVICE_TIMEOUT={{ env_vars.org_service_timeout }}
CLD_SERVICE_TIMEOUT={{ env_vars.cld_service_timeout }}
