################# {{ env_code }} ####################################### 

#### [Start] - Dev/Local/{{ env_code }} property file details
IGWAPI_ENDPOINT={{ env_vars.igwapi_endpoint }}
IGWAPI_REGULARPRODUCT_ENDPOINT={{ env_vars.igwapi_regularproduct_endpoint }}
IGWAPI_REQPARAMS_ENDPOINT={{ env_vars.igwapi_reqparams_endpoint }}
Igw-App-Key={{ vault[app].igw_app_key }}
IGW_CORELATIONID={{ env_vars.igw_corelationid }}
IGW_SLA_DAYS=5
IGW_CONSUMER_APP=O_AP_SYMPH
IGW_TEST_REQUEST=false

OIDM_API_ENDPOINT={{ env_vars.oidm_api_endpoint }}
# This authorization code is valid for user id GLDIGW1
OIDM_AUTHORIZATION_CODE={{ vault[app].oidm_auth_code }}
OIDM_X-OAUTH-IDENTITY-DOMAIN-NAME={{ env_vars.oidm_x_oauth_identity_domain_name }}
OIDM_GRANT_TYPE=CLIENT_CREDENTIALS
OIDM_SCOPE={{ env_vars.oidm_scope }}
OIDM_TOKEN_EXPIRY=1000000
BIPSERVICE_ENDPOINT={{ env_vars.bip_service_endpoint }}
FUTURESTATE_ENDPOINT={{ env_vars.futurestate_endpoint }}
IGWAPI_ORG_SEARCH_CRITRIA_ENDPOINT={{ env_vars.igwapi_org_search_criteria_endpoint }}
IGWAPI_ORG_SEARCH_ENDPOINT={{ env_vars.igwapi_org_search_endpoint }}
#### [End] - Dev/Local/{{ env_code }} property file details

########### {{ env_code }} ############################
JNDI_URL=iiop://localhost:{{ env_vars.was_bootstrap_port }}
JNDI_DS_SYMPHONY={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].sym_db_name)) | join(" ") }}
JNDI_DS_REPORTS={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].rep_db_name)) | join(" ") }}

# ILL Properties

IGWAPI_ILL_REGULARPRODUCT_ENDPOINT={{ env_vars.ill_igwapi_regularproduct_endpoint }}
ILL_Igw-App-Key={{ vault[app].ill_igw_app_key }}
ILL_IGW_CORELATIONID={{ env_vars.ill_igw_corelationid }}
ILL_IGW_SLA_DAYS=5
ILL_IGW_CONSUMER_APP=O_AP_SYMPH

ILL_OIDM_API_ENDPOINT={{ env_vars.ill_oidm_api_endpoint }}
ILL_OIDM_AUTHORIZATION_CODE={{ vault[app].ill_oidm_auth_code }}
ILL_OIDM_X-OAUTH-IDENTITY-DOMAIN-NAME={{ env_vars.ill_oidm_x_oauth_identity_domain_name }}
ILL_OIDM_GRANT_TYPE=CLIENT_CREDENTIALS
ILL_OIDM_SCOPE={{ env_vars.ill_oidm_scope }}
ILL_OIDM_TOKEN_EXPIRY=1000000
