# if set to 1 the ConfigFilePath read from the JndiConfigUrl
# otherwise a standard ConfigFile will be taken
ReadConfigFileURLFromJNDI=1

#JNDI-Name for URL for engineConfiguration
JndiConfigFileUrl=java:comp/env/url/pricingConfig


# configuration file for log4j
log4j-config={{ env_vars.log4j_config }}


# web-service connection
#BC3D
ServiceEndpoint={{ env_vars.service_endpoint}}

# Number of Threads for starting Process in WSEngine.java
Num_Processes=6

# Number of Simulation Years
Num_Years=100000

# Number of positions for rounding in the new Method
RoundingPosition=4

#Timeout for Axis in MilliSeconds
AxisTimeOut=2100000


#set to 1 to using WorkManager of Websphere otherwise using Standard Java ThreadService
#For using WorkManager it must be configured in WS-AdminConsole
UseWorkManager=1

#Name of WorkManager configured in Websphere Server
WorkManagerName=java:comp/env/wm/pricingwm

#Timeout for WorkManager in MilliSeconds
WorkManagerTimeOut=2105000


# make it possible to distribute Requests to different Servers. Default: disabled.
# Field "Num_MultiHost_Server" corresponds to the last Charachter in Field "MultiHostDistributionServiceEndpoint"
# Setting "ActivateMultiHostDistribution=1" starts on every following Server the defined Number of WebServices for calculating
ActivateMultiHostDistribution=0
Num_MultiHost_Server=2
MultiHostDistributionServiceEndpoint_1=
MultiHostDistributionServiceEndpoint_2=

