stageconfig.datafile=/home/webadmn/bip
stageConfig.proxyHost=
stageConfig.proxyPort=
stageConfig.log4jConfig=

stageConfig.serviceEndpoint={{ env_vars.stageconfig_serviceendpoint }}
stageConfig.bipproperties={{ env_vars.stageconfig_bipproperties }}
stageConfig.graydonBeUser={{ vault[app].graydonbe_user }}
stageConfig.graydonBePassword={{ vault[app].graydonbe_password }}
stageConfig.graydonBeDirectory=/BIPMONITORINGLOADS/BE/transit
stageConfig.graydonBeUrl=https://portal400.graydon.be:10447/Servlet/XmlAccessClient
stageConfig.graydonBeClientNumber={{ env_vars.stageconfig_graydonbeclientnumber }}