LDAP_PROVIDER_URL={{ env_vars.ldap_provider_url }}
# As many OID Paths to be authenticated against; seperated by "|"
PATH=internal\,cn=Users\,dc=atradiusnet\,dc=com|external\,cn=Users\,dc=atradiusnet\,dc=com