JNDI_URL=iiop://localhost:{{ env_vars.was_bootstrap_port }}
JNDI_DS_SYMPHONY={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].sym_db_name)) | join(" ") }}
JNDI_DS_REPORTS={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].rep_db_name)) | join(" ") }}

GENESIS_ENDPOINT={{ env_vars.genesis_endpoint }}
FUTURESTATE_ENDPOINT={{ env_vars.futurestate_endpoint }}
GENESIS_USERID={{ vault[app].gbipr_genesis_user }}
GENESIS_PASSWORD={{ vault[app].gbipr_genesis_password }}

#DNB Info Report Display
DnB.InfoReportDisplay.Product.Mapping={{ env_vars.dnb_inforeportdisplay_product_mapping}}
#DNB Uniform Report Display
DnB.UniformReportDisplay.Product.Mapping={{ env_vars.dnb_uniformreportdisplay_product_mapping }}
