# The path of the files will be :
# PATH + NAME_INPUT_FILE + reference + EXTENSION
# reference is the request parameter named 'reference'.
# type is the request parameter named 'Type'
NAME_INPUT_FILE = CyCPolicies

# if type <> DEFAUT_TYPE, the path of the files will be :
# PATH + NAME_xxxx_FILE + reference + "_" + type + EXTENSION
# if type == DEFAUT_TYPE, the path of the files will be :
# PATH + NAME_xxxx_FILE + reference + EXTENSION
NAME_TEMP_FILE = tmp_CyCPolicies
NAME_OUTPUT_FILE = CyCPoliciesErrors

# default type
# the defaut type won't appear in the tmp and output file name.
DEFAUT_TYPE = Regular

#extension
EXTENSION = .csv

#linux
PATH = {{ env_vars.file_path }}

#windows
#for windows \ need to be double : \\
#PATH = C:\\cyc\\

END_POINT = {{ env_vars.end_point }}

#Error description
E001 = Function code not correct
E002 = Organisation does not exist
E003 = Trade sector does not exist
E004 = Wrong function code for a non existing policy
E005 = Wrong function code for an existing policy
E006 = Trade Code has not changed
E007 = CYC policy number which has to be exchanged does not exist
E008 = Transfer of credit limits failed

# Changes done for CyC Brazil CoE Phase 2 by inrran1 on Date 20-08-2013 - Start
E011 = Currency does not exist
E012 = Policy currency of old and new policy are not the same
# Changes done for CyC Brazil CoE Phase 2 by inrran1 on Date 20-08-2013 . End

VA02 = The validation of the row failed
WS03 = The webservice throw an error
WS08 = The webservice throw a critical error
