############# Replacing Contract Texts of the linked policy of a finance policy #############
1_verzekerde=Exporteur
2_medeverzekerde=Subcontractant
3_debiteur=Koper
4_financier=Verzekerde
5_herfinancier=Verzekerde
6_leningnemer=Debiteur
7_verzekerde/lessor=Fabrikant
8_debiteur/lessee=Koper
