# database userid and password
userID={{ vault[app].sym_db_user }}
password={{ vault[app].sym_db_password }}
XBRL={{ vault[app].xbrl_user }}
reportsDBUser={{ vault[app].rep_db_user }}
reportsDBPasswd={{ vault[app].rep_db_password }}

#*------------------------------------------------------------------------------------
#List of properties for French BIP.
##Start of  GetReport properties
ncm.bip.frareportrequest.URL=https://services.data-access-gateway.com/sda/requetes/infos.asp
ncm.bip.fraenquiry.URL=https://services.data-access-gateway.com/sda/requetes/enq_inconnue.asp
ncm.bip.fra.xslfilename=IdealWorld.xsl

#
#*-------------------------------------------------------------------------------------

# * Start of  Mailbox ( French CM ) properties
#External
ncm.bip.cm.FRA.host=xfer.dsi-info.net
ncm.bip.cm.FRA.port=6322
ncm.bip.cm.FRA.userid={{ vault[app].ncmbipcmfra_user }}
ncm.bip.cm.FRA.password={{ vault[app].ncmbipcmfra_password }}
ncm.bip.cm.FRA.sftpfolder={{ env_vars.ncmbipcmfra_sftpfolder }}

#Internal
ncm.bip.cm.FRA.retrycount=100
ncm.bip.cm.FRA.cce.downloadNotices=N
ncm.bip.cm.FRA.cce.downloadReports=Y
ncm.bip.cm.FRA.cce.notices.file.extn=.xml
ncm.bip.cm.FRA.cce.reports.file.extn=.xml
ncm.bip.cm.FRA.cce.retentionperiod=90
ncm.bip.fra.contractID=16947
