# database userid and password
XBRL={{ vault[app].xbrl_user }}
userID={{ vault[app].sym_db_user }}
password={{ vault[app].sym_db_password }}
reportsDBUser={{ vault[app].rep_db_user }}
reportsDBPasswd={{ vault[app].rep_db_password }}
BUSINESS_LOG_FOLDER=DNK_119

# Start of properties used for Experian get reports
ncm.bip.dnk_experian.URL=https://kobopen.kob.dk/uk/xml.asp

# login elapse time in hhmm
ncm.bip.dnk_experian.logon_elapse_time=0005

#mrf50214 04/09/24
ncm.bip.dnk_experian.logon.URL=https://kobopen.kob.dk/api/Logon
ncm.bip.dnk_experian.xslfilename=ReportStyle.xsl

# Start of properties used for Experian CM ON requests
ncm.bip.dnk_experian.cmon_AKSkey={{ vault[app].dnk_experian_cmon_akskey }}
ncm.bip.dnk_experian.cmon_AKSpassword={{ vault[app].dnk_experian_cmon_akspassword }}
ncm.bip.dnk_experian.cmon_UserID={{ vault[app].dnk_experian_cmon_user }}
ncm.bip.dnk_experian.cmon_Password={{ vault[app].dnk_experian_cmon_password }}

# Start of properties used for Experian Constant Monitoring
ncm.bip.dnk_experian.cm_MaxErrors=3
ncm.bip.dnk_experian.monitoring_URL={{ env_vars.ncm_bip_dnk_experian_monitoring_url }}
