ebaz.report.env.name={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].db_name' | format(vault[app].sym_db_name)) | join(" ") }}
ebaz.smtp.server.name={{ env_vars.ebaz_smtp_server_name }}
ebaz.report.to.email.ids=USD@atradius.com
