# Start of properties used by DBConnectionManager

### How the DBConnectionManager reads these properties:
### ==================================================================
### The property ncm.framework.ds.<db-name>.id maps to a  logical name
### for a datasorce.
###
### ncm.framework.ds.<logical-name>.provider-url: maps to the JNDI
### provider URL for the datasource.
###
### ncm.framework.ds.<logical-name>.factory : maps to the factory
### implementation class for the JNDI provider
###
### ncm.framework.ds.<logical-name>.jndi-name : maps to the JNDI name
### of the datasource

ncm.framework.ds.default.id=A
ncm.framework.ds.xbrl.id=X
ncm.framework.ds.X.provider-url=iiop://localhost:{{ env_vars.was_bootstrap_port }}
ncm.framework.ds.X.factory=com.ibm.websphere.naming.WsnInitialContextFactory
ncm.framework.ds.X.jndi-name={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].rep_db_name)) | join(" ") }}
ncm.framework.ds.A.provider-url=iiop://localhost:{{ env_vars.was_bootstrap_port }}
ncm.framework.ds.A.factory=com.ibm.websphere.naming.WsnInitialContextFactory
ncm.framework.ds.A.jndi-name={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].sym_db_name)) | join(" ") }}

# End of properties used by DBConnectionManager
# ejb context parameters
ncm.framework.utils.ejbJndiProviderURL=iiop://localhost:{{ env_vars.was_bootstrap_port }}
ncm.framework.utils.ejbJndiCtxFactory=com.ibm.websphere.naming.WsnInitialContextFactory
