documentservice.genesis.password={{ vault[app].documentservice_genesis_password }}
documentservice.genesis.security=N
documentservice.genesis.capturelocation=CRDIFF
documentservice.genesis.document_file_type=BUINF
documentservice.genesis.document_class=BUINF_C1
ebazpdflocation=/watson_de

#MRF48292 DMS API Integration 29/01/2024
documentservice.genesis.user={{ vault[app].documentservice_genesis_user }}
dmsservice.store.url={{ env_vars.dmsservice_store_url }}

#OIDM Properties
oidm.get_token.environment={{ env_vars.oidm_get_token_environment }}
oidm.get_token.url={{ env_vars.oidm_get_token_url }}
oidm.get_token.basic_auth={{ vault[app].oidm_get_token_basic_auth }}
oidm.get_token.scope={{ env_vars.oidm_get_token_scope }}
oidm.get_token.domain={{ env_vars.oidm_get_token_domain }}

############ DMS SERVICE PROPERTIES ############
dmsservice.header.application=BIP
dmsservice.header.invocationservice=http://atradius.com/bip/documents
dmsservice.header.correlationid=bip123
dmsservice.header.msgid=bip456

#Time in miliseconds. 3000000 ms - > 50 minutes
oidm.get_token.timer=3000000

#MRF50315 25/09/2024
ebaz.sftp.hostname={{ env_vars.ebaz_sftp_hostname }}
ebaz.sftp.port=22
ebaz.sftp.username={{ vault[app].ebaz_sftp_username }}
ebaz.sftp.password={{ vault[app].ebaz_sftp_password }}
ebaz.sftp.foldername=DE
