DEFAULT_LANGUAGE=EN

##############  File Location Properties  ##############
LOCAL_FILE_PATH={{ env_vars.local_file_path }}

##############  File Naming Properties  ##############
JRNL_SRC_TRANS_FILE_FORMAT=CGLIJournalSrcTransfer.txt
JRNL_TRANS_2_PRUD_FILE_FORMAT=CGLIJournalTransfer2Prudence.txt
JRNL_VALIDATION_FILE_FORMAT=CGLIJournalValidation.txt
