## Start of properties used by DBConnectionManager

ncm.framework.ds.default.id=G


ncm.framework.ds.G.provider-url=iiop://localhost:{{ env_vars.was_bootstrap_port }}
ncm.framework.ds.G.factory=com.ibm.websphere.naming.WsnInitialContextFactory
ncm.framework.ds.G.jndi-name={{ env_vars.jdbc_datasource_list | json_query('[?db_name==`%s`].jndi_name' | format(vault[app].sym_db_name)) | join(" ") }}


## End of properties used by DBConnectionManager
