- name: Sync All Active Nodes on Deployment Manager
  tags: sync_nodes
  delegate_to: "{{ env_vars.dmgr_host }}"
  run_once: true
  block:
    - name: Perform Node Sync
      ansible.builtin.command: >
        {{ dmgr_profile_dir }}/bin/wsadmin.sh -conntype SOAP -lang jython -c "AdminNodeManagement.syncActiveNodes()"
      register: sync_node_output
      changed_when: true

    - name: Node Synced status
      ansible.builtin.debug:
        var: sync_node_output.stdout
      when: sync_node_output is defined
