# Properties file.

#Endpoints for called WEB-SERVICES
URL_WS_CLD={{ env_vars.url_ws_cld }}
URL_WS_ORG={{ env_vars.url_ws_org }}
URL_WS_TH={{ env_vars.url_ws_th }}

#CREDENTIALS FOR TH
WS_TH_USERID={{ vault[app].th_userid}}
#EMPTY PASSWORD STRING IS INTENDED
WS_TH_PASSWORD=

#TH_PROPERTIES
TH_BATCH_PREFIX={{ env_vars.th_batch_prefix }}
TH_PROJECT_SCOPE=
	#Remark:507000001
TH_SPECIMEN={{ env_vars.th_specimen }}

#JNDI PROPERTIES
PROVIDER_URL=iiop://localhost:{{ env_vars.was_bootstrap_port }}
INITIAL_CONTEXT_FACTORY=com.ibm.websphere.naming.WsnInitialContextFactory

#JMS Connection Properties
DP_OUTPUT_FILEPATH={{ env_vars.dp_output_filepath }}

#End-point to determine if the invoice must be processed by OPUS or OMS
CIBT_ACCOUNTING_NOTE_URL={{ env_vars.cibt_accounting_note_url }}
ATR_ORIGIN_USER_ID={{ vault[app].atr_origin_user_id }}
ATR_ORIGIN_APPLICATION={{ env_vars.atr_origin_application }}

################################# Authentication API properties #################################
OAUTH_TOKEN_URL={{ env_vars.oauth_token_url }}
CLIENT_ID={{ vault[app].cibt_client_id }}
CLIENT_SECRET={{ vault[app].cibt_client_secret }}
SCOPE={{ env_vars.cibt_scope }}
IDENTITY_DOMAIN={{ env_vars.identity_domain }}
