#Administrator Login Details.
USER={{ vault[app].amt_userid }}
PASSWORD={{ vault[app].amt_app_key }}

#Base Folder Id 
BASE_FOLDER={{ env_vars.base_folder_value }}

#Authentication type
AUTHTYPE=secEnterprise

#Currency Prompt
CURRENCY=Enter Currency

#Policy Prompt
POLICY_ID=Enter Policy Id

#Case Prompt
CASE_ID=Enter Case Id

#Case Prompt
CASE_ID=Enter Case Id

#CL Income
CL_INCOME=CL Income

#Claims
CLAIMS= Claims

#Policy Details
POLICY_DETAILS=Policy Details

#Risk Premium
RISK_PREMIUM= Risk Premium

#Risk Premium
REPORT_URL={{ env_vars.report_url }}

CMS_SERVER_URL= {{ env_vars.cms_server_url }}
