stageconfig.datafile=/home/webadmn/bip
stageConfig.proxyHost=
stageConfig.proxyPort=
stageConfig.log4jConfig=
stageConfig.serviceEndpoint={{ env_vars.stageconfig_serviceendpoint }}
stageConfig.bipproperties={{ env_vars.stageconfig_bipproperties }}

# CHG0075288 09/06/2025

stageConfig.tokenUrl={{ env_vars.stageconfig_tokenurl }}
stageConfig.tokenContentType=application/json
stageConfig.charsetIrl=utf-8
stageConfig.clientId={{ vault[app].stageconfig_clientid }}
stageConfig.clientSecret={{ vault[app].stageconfig_clientsecret }}
stageConfig.tokenExpiry=1800
stageConfig.username={{ vault[app].stageconfig_user }}
stageConfig.password={{ vault[app].stageconfig_password }}
stageConfig.orgSearchUrl={{ env_vars.stageconfig_orgsearchurl }}
stageConfig.contentType=text/xml
stageConfig.namespaceIrl=http://schemas.xmlsoap.org/soap/envelope/
stageConfig.bodyTagOrgSearch=tem:BusinessSearch
stageConfig.offlineReportUrl={{ env_vars.stageconfig_offlinereporturl }}
stageConfig.bodyTagofflineReport=tem:orderreport
stageConfig.onlineReportUrl={{ env_vars.stageconfig_onlinereporturl }}
stageConfig.bodyTagOnlineReport=tem:BusinessReport
stageConfig.reportType=FULL
stageConfig.retrieveMonitoringUrl={{ env_vars.stageconfig_retrievemonitoringurl }}
stageConfig.startMonitoringUrl={{ env_vars.stageconfig_startmonitoringurl }}
stageConfig.bodyTagStartMonitoring=tem:addMonitoringResult
stageConfig.stopMonitoringUrl={{ env_vars.stageconfig_stopmonitoringurl }}
stageConfig.bodyTagStopMonitoring=tem:removemonitoring
