USER={{ vault[app].user }}
PASSWORD={{ vault[app].password }}
#File location where organisations containing Orgid vs org names are written.
WRITEPATH={{ env_vars.write_path }}
READUSERPATH={{ env_vars.read_userpath }}
